name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-action@stable
      with:
        toolchain: stable
        components: rustfmt, clippy
    
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo index
      uses: actions/cache@v4
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Cache cargo build
      uses: actions/cache@v4
      with:
        path: target
        key: ${{ runner.os }}-cargo-build-target-${{ hashFiles('**/Cargo.lock') }}
    
    - name: Run unit tests - auria-core
      run: cd auria-core && cargo test --lib
    
    - name: Run unit tests - auria-tensor
      run: cd auria-tensor && cargo test --lib
    
    - name: Run unit tests - auria-router
      run: cd auria-router && cargo test --lib
    
    - name: Run unit tests - auria-execution
      run: cd auria-execution && cargo test
    
    - name: Run unit tests - auria-node
      run: cd auria-node && cargo test --lib
    
    - name: Run unit tests - auria-license
      run: cd auria-license && cargo test --lib
    
    - name: Run unit tests - auria-settlement
      run: cd auria-settlement && cargo test --lib
    
    - name: Run integration tests - auria-execution
      run: cd auria-execution && cargo test --test inference_pipeline

  clippy:
    name: Clippy Lints
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-action@stable
      with:
        toolchain: stable
        components: clippy
    
    - name: Run clippy
      run: |
        cargo clippy --workspace --all-targets --all-features -- -D warnings -A dead_code

  rustfmt:
    name: Rust Format
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-action@stable
      with:
        toolchain: stable
        components: rustfmt
    
    - name: Check formatting
      run: cargo fmt --all -- --check

  doc:
    name: Documentation
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-action@stable
      with:
        toolchain: stable
    
    - name: Build documentation
      run: cargo doc --workspace --no-deps --document-private-items
      env:
        RUSTDOCFLAGS: -D warnings

  bench:
    name: Benchmarks
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-action@stable
      with:
        toolchain: stable
    
    - name: Run benchmarks
      run: cd auria-tensor && cargo bench --no-run
