name: Cross-Platform Test

on:
  push:
    branches: [ main, develop ]
  pull_request:

jobs:
  test_macos:
    name: Test (macOS)
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-action@stable
    
    - name: Run tests
      run: cargo test --workspace

  test_windows:
    name: Test (Windows)
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-action@stable
    
    - name: Run tests
      run: cargo test --workspace

  test_linux:
    name: Test (Linux)
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-action@stable
    
    - name: Run tests
      run: cargo test --workspace
